services:

  server:
    build: server/
    ports:
      - "3000:3000"
    depends_on:
      database:
        condition: service_healthy
    environment:
      - DB_HOST=database
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=novaDB

  app:
    build: app/
    ports:
      - "5173:5173"
    depends_on:
      - server

  database:
    image: postgres:latest
    container_name: nova_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: novaDB
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - nova_postgres:/var/lib/postgresql/data

volumes:
  nova_postgres:
